export const AboutContent = [
  "About Me:",
  `Hi fellas, I am <p class="text-blue-500 text-8xl"> Mayank Verma</p>`,
  `A Full Stack Developer more specialize in <span class="text-terminal-redText"> Backend Technologies </span> and <span class="text-terminal-redText"> Open Source</span> enthusiast`,
  "passionate about creating innovative solutions using modern technologies.",
  "",
  "Skills:",
  `• Languages: <span class="text-terminal-redText"> Javascript, Typescript, Java</span>`,
  `• Frontend:<span class="text-terminal-redText"> React, Astro docs, Tailwind CSS</span>`,
  `• Backend: <span class="text-terminal-redText">Node.js, Express</span>`,
  `• Databases:<span class="text-terminal-redText"> MongoDB, PostgreSQL, MySQL</span>`,
  `• Testing: <span class="text-terminal-redText"> Jest, Nightwatch</span>`,
  `• Tools: <span class="text-terminal-redText"> Git, Github Actions, Docker</span>`,
  "",
  "Type 'cd ..' or '..' or click on home to go back",
];
